variables:
  BASE_IMAGE: $CI_PROJECT_PATH:base-$CI_COMMIT_REF_NAME
  LINT_IMAGE: $CI_PROJECT_PATH:lint-$CI_COMMIT_REF_NAME

image: $BASE_IMAGE

before_script:
  - mkdir -p $GOPATH/src/github.com/nec-blockchain
  - ln -s $PWD $GOPATH/src/github.com/nec-blockchain/minbft
  - cd $GOPATH/src/github.com/nec-blockchain/minbft

stages:
  - build-base-image
  - build
  - test
  - build-lint-image
  - lint

build-base-image:
  stage: build-base-image
  image: docker:latest
  before_script:
  script:
    - docker build -t $BASE_IMAGE dockerfiles/base

build:
  stage: build
  script:
    - make build

test:
  stage: test
  script:
    - make check SGX_MODE=SIM

build-lint-image:
  stage: build-lint-image
  image: docker:latest
  before_script:
  script:
    - docker build -t $LINT_IMAGE --build-arg BASE_IMAGE=$BASE_IMAGE dockerfiles/lint

lint:
  stage: lint
  image: $LINT_IMAGE
  allow_failure: true
  script:
    - make lint
